In [9]:
# DECISION TREE UNTUK REGRESSION
import pandas as pd # untuk membaca data
import numpy as np # untuk mengolah data
import matplotlib.pyplot as plt # membuat grafik

In [10]:
# PREPROCESS
# membaca data csv yang di importkan
mpg = pd.read_csv('./dataset/auto.csv')
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [11]:
# Membaca data dengan menggunakan dummies
# Dummies digunakan untukmengkonvert/mengubah variabel kategori ke dalam variabel numerik
# Dengan melakukan proses One-Hot-Encode terhadap variabel kategori
mpg = pd.get_dummies(mpg)
mpg.head()

,mpg,cylinders,displacement,weight,acceleration,model year,origin,horsepower_100,horsepower_102,horsepower_103,...,car name_volvo 145e (sw),car name_volvo 244dl,car name_volvo 245,car name_volvo 264gl,car name_volvo diesel,car name_vw dasher (diesel),car name_vw pickup,car name_vw rabbit,car name_vw rabbit c (diesel),car name_vw rabbit custom
0,18.0,8,307.0,3504,12.0,70,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,15.0,8,350.0,3693,11.5,70,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,18.0,8,318.0,3436,11.0,70,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,16.0,8,304.0,3433,12.0,70,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,17.0,8,302.0,3449,10.5,70,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
# Mengubah data dari kolom menjadi baris
mpg.head().transpose()

                                    0       1       2       3       4
mpg                              18.0    15.0    18.0    16.0    17.0
cylinders                         8.0     8.0     8.0     8.0     8.0
displacement                    307.0   350.0   318.0   304.0   302.0
weight                         3504.0  3693.0  3436.0  3433.0  3449.0
acceleration                     12.0    11.5    11.0    12.0    10.5
...                               ...     ...     ...     ...     ...
car name_vw dasher (diesel)       0.0     0.0     0.0     0.0     0.0
car name_vw pickup                0.0     0.0     0.0     0.0     0.0
car name_vw rabbit                0.0     0.0     0.0     0.0     0.0
car name_vw rabbit c (diesel)     0.0     0.0     0.0     0.0     0.0
car name_vw rabbit custom         0.0     0.0     0.0     0.0     0.0

[406 rows x 5 columns]

In [15]:
# Mengimport model train_test_split untuk ngesplit sebagian data train menjadi data testing
from sklearn.model_selection import train_test_split

# Memilih kolom data suntuk sumbu x dengan menghapus kolom mpg
X = mpg.drop('mpg', axis='columns')

# Memilih kolom data untuk sumbu y berisi seluruh data mpg
y = mpg['mpg']

# Data testing diambil dari 20% data training menggunakan 'test_size=0.2'
# Data testing diambil dari 1 kolom dari data training menggunakan 'random_state=3'
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [16]:
from sklearn.tree import DecisionTreeRegressor

# Memanggil model Decision Tree Regression (dt)
# Dengan kedalaman = 8, jumlah minimum sampel yang diperlukan berada pada leaf node = 0.13 atau 13%, dan kolom yang diambil = 3
dt = DecisionTreeRegressor(max_depth=8, min_samples_leaf=0.13, random_state=3)

# Menggunakan fungsi fit untuk menyesuaikan model dt dengan data training
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=8, min_samples_leaf=0.13, random_state=3)

In [17]:
# MENGEVALUASI REGRESSION TREE
# RMSE model mengukur rata-rata, seberapa besar prediksi model yang dihasilkan berbeda dari label yang sebenarnya.
# RMSE model dapat diperoleh dengan menghitung akar kuadrat dari model Mean Squared Error (MSE).

# Mengimport matriks model mean squared error
from sklearn.metrics import mean_squared_error

# Menentukan hasil prediksi dari x_test
y_pred = dt.predict(X_test)

# Menghitung mse
mse_dt = mean_squared_error(y_test, y_pred)

# Menghitung root MSE
# RSME diperoleh dari akar kuadrat dari MSE
rmse_dt = mse_dt ** (1/2)

# Print hasil RMSE
print("Test set RMSE dt: {:.2f}".format(rmse_dt))

Test set RMSE dt: 3.68

In [18]:
# Mengimport model linear regression
from sklearn.linear_model import LinearRegression

# Memanggil fungsi linear dengan variabel lr
lr = LinearRegression()

# fit atau sesuaikan pada model lr
lr.fit(X_train, y_train)

LinearRegression()

In [19]:
# Memprediksi linier regression
y_pred_lr = lr.predict(X_test)

# Menghitng MSE model lr
mse_lr = mean_squared_error(y_test, y_pred_lr)

# Menghitung RMSE model lr diperoleh dari akar kuadrat dari MSE model Linear Regression
rmse_lr = mse_lr ** 0.5

# Print rmse_lr
print("Linear Regression test set RMSE: {:.2f}".format(rmse_lr))

# Print rmse_dt
print("Regression Tree test set RMSE: {:.2f}".format(rmse_dt))

Linear Regression test set RMSE: 4.07
Regression Tree test set RMSE: 3.68